# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Shared
      autoload :ApiResponse, 'open_api_sdk/models/shared/apiresponse.rb'
      autoload :Category, 'open_api_sdk/models/shared/category.rb'
      autoload :Order, 'open_api_sdk/models/shared/order.rb'
      autoload :OrderStatus, 'open_api_sdk/models/shared/order_status.rb'
      autoload :Pet, 'open_api_sdk/models/shared/pet.rb'
      autoload :PetInput, 'open_api_sdk/models/shared/pet_input.rb'
      autoload :PetStatus, 'open_api_sdk/models/shared/pet_status.rb'
      autoload :Security, 'open_api_sdk/models/shared/security.rb'
      autoload :Tag, 'open_api_sdk/models/shared/tag.rb'
      autoload :User, 'open_api_sdk/models/shared/user.rb'
    end
  end
end
