# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class Order
        extend T::Sig
        include Crystalline::MetadataFields


        field :id, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }

        field :pet_id, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('petId') } }

        field :quantity, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('quantity') } }

        field :ship_date, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('shipDate'), 'decoder': Utils.datetime_from_iso_format(true) } }
        # Order Status
        field :status, Crystalline::Nilable.new(Models::Shared::OrderStatus), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('status'), 'decoder': Utils.enum_from_string(Models::Shared::OrderStatus, true) } }

        field :complete, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('complete') } }

        sig { params(id: T.nilable(::Integer), pet_id: T.nilable(::Integer), quantity: T.nilable(::Integer), ship_date: T.nilable(::DateTime), status: T.nilable(Models::Shared::OrderStatus), complete: T.nilable(T::Boolean)).void }
        def initialize(id: nil, pet_id: nil, quantity: nil, ship_date: nil, status: nil, complete: false)
          @id = id
          @pet_id = pet_id
          @quantity = quantity
          @ship_date = ship_date
          @status = status
          @complete = complete
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @pet_id == other.pet_id
          return false unless @quantity == other.quantity
          return false unless @ship_date == other.ship_date
          return false unless @status == other.status
          return false unless @complete == other.complete
          true
        end
      end
    end
  end
end
