# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
    

      class Category
        
        include Crystalline::MetadataFields


        field :id, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }

<<<<<<< ours
        field :name, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }
=======
        field :name, Crystalline::Nilable.new(::Boolean), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }
>>>>>>> theirs

        
        def initialize(id: nil, name: nil)
          @id = id
          @name = name
        end

        def print
          @id.to_s
        end
        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @name == other.name
          true
        end
      end
    end
  end
end
