# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
    
      # OrderStatus - Order Status
      class OrderStatus < T::Enum


        enums do
          PLACED = new('placed')
          APPROVED = new('approved')
          DELIVERED = new('delivered')
        end
      end
    end
  end
end
