# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
    

      class Security
        extend T::Sig
        include Crystalline::MetadataFields


        field :petstore_auth, Crystalline::Nilable.new(::String), { 'security': { 'scheme': true, 'type': 'oauth2', 'field_name': 'Authorization' } }

        sig { params(petstore_auth: T.nilable(::String)).void }
        def initialize(petstore_auth: nil)
          @petstore_auth = petstore_auth
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @petstore_auth == other.petstore_auth
          true
        end
      end
    end
  end
end
