# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class FindPetsByStatusRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Status values that need to be considered for filter
        field :status, Crystalline::Array.new(Models::Operations::Status), { 'query_param': { 'field_name': 'status', 'style': 'form', 'explode': true } }

        sig { params(status: T::Array[Models::Operations::Status]).void }
        def initialize(status:)
          @status = status
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @status == other.status
          true
        end
      end
    end
  end
end
