# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class GetInventorySecurity
        extend T::Sig
        include Crystalline::MetadataFields


        field :api_key, ::String, { 'security': { 'scheme': true, 'type': 'apiKey', 'sub_type': 'header', 'field_name': 'api_key' } }

        sig { params(api_key: ::String).void }
        def initialize(api_key:)
          @api_key = api_key
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @api_key == other.api_key
          true
        end
      end
    end
  end
end
