# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class Status < T::Enum


        enums do
          AVAILABLE = new('available')
          PENDING = new('pending')
          SOLD = new('sold')
        end
      end
    end
  end
end
