# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class UpdateUserRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # name that need to be updated
        field :username, ::String, { 'path_param': { 'field_name': 'username', 'style': 'simple', 'explode': false } }
        # Updated user object
        field :user, Models::Shared::User, { 'request': { 'media_type': 'application/json' } }

        sig { params(username: ::String, user: Models::Shared::User).void }
        def initialize(username:, user:)
          @username = username
          @user = user
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @username == other.username
          return false unless @user == other.user
          true
        end
      end
    end
  end
end
