# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class UpdatePetWithFormRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # ID of pet that needs to be updated
        field :pet_id, ::Integer, { 'path_param': { 'field_name': 'petId', 'style': 'simple', 'explode': false } }

        field :request_body, Crystalline::Nilable.new(Models::Operations::UpdatePetWithFormRequestBody), { 'request': { 'media_type': 'application/x-www-form-urlencoded' } }

        sig { params(pet_id: ::Integer, request_body: T.nilable(Models::Operations::UpdatePetWithFormRequestBody)).void }
        def initialize(pet_id:, request_body: nil)
          @pet_id = pet_id
          @request_body = request_body
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @pet_id == other.pet_id
          return false unless @request_body == other.request_body
          true
        end
      end
    end
  end
end
