# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class UploadFileRequestBody
        extend T::Sig
        include Crystalline::MetadataFields

        # Additional data to pass to server
        field :additional_metadata, Crystalline::Nilable.new(::String), { 'multipart_form': { 'field_name': 'additionalMetadata' } }
        # file to upload
        field :file, Crystalline::Nilable.new(Models::Operations::File), { 'multipart_form': { 'file': true, 'field_name': 'file' } }

        sig { params(additional_metadata: T.nilable(::String), file: T.nilable(Models::Operations::File)).void }
        def initialize(additional_metadata: nil, file: nil)
          @additional_metadata = additional_metadata
          @file = file
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @additional_metadata == other.additional_metadata
          return false unless @file == other.file
          true
        end
      end
    end
  end
end
